name: Build and Test (MinGW)

on:
  push:
    branches: [ "main", "dev_restructure" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: windows-2022
    if: github.event.head_commit.message == 'Test.'
    strategy:
      matrix:
        test_script: [TestMinGW_32.bat, TestMinGW_64.bat, TestMinGW_32_Wide.bat, TestMinGW_64_Wide.bat]
        include:
          - test_script: MinGW_MakeTest32.bat
            mingw_folder: llvm-mingw-20220906-ucrt-i686
            build_path: build/mingw_llvm/Win32/Release/
          - test_script: MinGW_MakeTest32_Wide.bat
            mingw_folder: llvm-mingw-20220906-ucrt-i686
            build_path: build/mingw_llvm/Win32/ReleaseWIDE/
          - test_script: MinGW_MakeTest64.bat
            mingw_folder: llvm-mingw-20220906-ucrt-x86_64
            build_path: build/mingw_llvm/x64/Release/       
          - test_script: MinGW_MakeTest64_Wide.bat
            mingw_folder: llvm-mingw-20220906-ucrt-x86_64
            build_path: build/mingw_llvm/x64/ReleaseWIDE/ 
    steps:
      - name: Install Checkout
        uses: actions/checkout@v3
        
      - name: Install MSYS
        uses: msys2/setup-msys2@v2
      
      - name: Download MinGW
        shell: msys2 {0}
        run: wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/${{ matrix.mingw_folder }}.zip -P C:/ 
          
      - name: Extract MinGW
        working-directory: C:\
        run: 7z x ${{ matrix.mingw_folder }}.zip
 
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: ./${{ matrix.test_script }} build
        
      - name: Test
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          $env:Path = "C:\${{ matrix.mingw_folder }}\bin;" + $env:Path 
          ./${{ matrix.build_path }}TrivailTestKit_Test.exe
      