name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build_and_test_release_32:
    runs-on: windows-2019

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build 
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=Release /property:Platform=x86 /p:PlatformToolset=v143/v142/v141
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: Release/Test.exe
      
  build_and_test_release_64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build 
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=Release /property:Platform=x64 /p:PlatformToolset=v143/v142/v141
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: x64/Release/Test.exe

  build_and_test_release_wide_32:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build 
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=ReleaseWide /property:Platform=x86 /p:PlatformToolset=v143/v142/v141
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ReleaseWide/Test.exe
      
  build_and_test_release_wide_64:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build 
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=ReleaseWide /property:Platform=x64 /p:PlatformToolset=v143/v142/v141
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: x64/ReleaseWide/Test.exe
