name: Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      
    - name: Build Release 32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=Release /property:Platform=x86
      
    - name: Build Release 64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=Release /property:Platform=x64

    - name: Build ReleaseWide 32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=ReleaseWide /property:Platform=x86
      
    - name: Build ReleaseWide 64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=ReleaseWide /property:Platform=x64


  test:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
      
    - name: Test Release 32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: call Release\\Test.exe
      
    - name: Build Release 64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: call x64\\Release\\Test.exe

    - name: Build ReleaseWide 32
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: call ReleaseWide\\Test.exe
      
    - name: Build ReleaseWide 64
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: call x64\\ReleaseWide\\Test.exe
