name: Build and Test (MinGW CLang LLVM)

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: windows-2022

    strategy:
      matrix:
        build_mode: [Release, ReleaseWIDE, Debug, DebugWIDE]
        architecture: [32, 64]
        include:
          - architecture: 32
            mingw_folder: llvm-mingw-20220906-ucrt-i686
            arch_folder: Win32
          - architecture: 64
            mingw_folder: llvm-mingw-20220906-ucrt-x86_64
            arch_folder: x64
    steps:
      - name: Install Checkout
        uses: actions/checkout@v3
        
      - name: Install MSYS
        uses: msys2/setup-msys2@v2
      
      - name: Download MinGW
        shell: msys2 {0}
        run: wget https://github.com/mstorsjo/llvm-mingw/releases/download/20220906/${{ matrix.mingw_folder }}.zip -P C:/ 
          
      - name: Extract MinGW
        working-directory: C:\
        run: 7z x ${{ matrix.mingw_folder }}.zip
 
      - name: Build
        working-directory: ${{env.GITHUB_WORKSPACE}}
        run: |
          $env:Path = "C:\${{ matrix.mingw_folder }}\bin;" + $env:Path 
          ./MinGW_MakeTest.bat build ${{ matrix.build_mode }} ${{ matrix.architecture }}
        
      - name: Test
        working-directory: ${{env.GITHUB_WORKSPACE}}\build\mingw_llvm\${{ matrix.arch_folder }}\${{ matrix.build_mode }}
        run: |
          $env:Path = "C:\${{ matrix.mingw_folder }}\bin;" + $env:Path 
          ./TrivialTestKit_Test.exe
      