name: Build and Test (Visual Studio)

on:
  push:
    branches: [ "main", "dev_restructure" ]
  pull_request:
    branches: [ "main" ]

env:
  SOLUTION_FILE_PATH: .

permissions:
  contents: read

jobs:
  build_and_test:
    strategy:
      matrix:
        os: [windows-2019, windows-2022]
        platform: [x86, x64]
        configuration: [Release, ReleaseWIDE]
        include:
          - os: windows-2019
            toolset: v142
          - os: windows-2022
            toolset: v143
          - platform: x86
            pathprefix: Win32
          - platform: x64
            pathprefix: x64
  
    runs-on: ${{ matrix.os }}
    
    if: github.event.head_commit.message == 'Test.'

    steps:
    - uses: actions/checkout@v3

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2

    - name: Build 
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: MSBuild /m /property:Configuration=${{ matrix.configuration }} /property:Platform=${{ matrix.platform }} /p:PlatformToolset=${{ matrix.toolset }}
      
    - name: Test
      working-directory: ${{env.GITHUB_WORKSPACE}}
      run: ./build/vs/${{ matrix.pathprefix }}/${{ matrix.configuration }}/TrivialTestKit_Test.exe
